aon/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app import views

urlpatterns = [

    # Admin URL
    url(r'^admin/', admin.site.urls),

    # Account,Profile URLs
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^account/setting/$', views.account_edit, name='edit_account'),
    url(r'^profile/edit/$', views.edit_profile_view, name='edit_profile'),
    url(r'^avatar/', include('avatar.urls')),


    # Project URLs
    url(r'^explore/$', views.explore, name='explore'),
    url(r'^explore/(?P<category_name>[\w-]+)/$', views.filter_projects, name='explore_filter'),
    url(r'^projects/(?P<slug>[\w-]+)/$', views.detail_view, name='project_detail'),
    url(r'^projects/(?P<slug>[\w-]+)/edit', views.edit_view, name='edit_view'),
    url(r'^projects/(?P<slug>[\w-]+)/delete', views.delete_view, name='delete_view'),
    url(r'^search$', views.search, name='search'),

    # Notification
    url(r'^notifications/$', views.notifications, name='notifications'),

    # Offer/Collaborate
    url(r'^offer/accept/$', views.acceptOffer, name='acceptOffer'),
    url(r'^offer/reject/$', views.rejectOffer, name='rejectOffer'),
    url(r'^projects/(?P<slug>[\w-]+)/collaborate/$', views.offer, name='offer'),

    # Profile,Dashboard URL's
    url(r'^users/(?P<user_name>[\w-]+)/$', views.users_profile_view, name='user_profile'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),

    # Static pages
    url(r'^$', views.indexView, name='index'),

    # AJAX
    url(r'^ajax/project/categories/$', views.get_project_categories, name='get_project_categories'),
    url(r'^ajax/project/sub_categories/$', views.get_project_types, name='get_project_types'),
    url(r'^ajax/project/skill_tags/$', views.get_skill_tags, name='get_skill_tags'),
    url(r'^ajax/project/update_progress', views.change_project_status, name='change_project_status'),
    url(r'^ajax/skill_tags/$', views.get_tags, name='get_tags'),
    url(r'^ajax/project/filter/$', views.filter_project, name='filter_project'),
    url(r'^ajax/project/get/$', views.get_project, name='get_project'),
    url(r'^ajax/post/requestoffer/$', views.create_request_offer, name='get_project'),
    url(r'^ajax/project/new/$', views.project_create, name='create_project'),

]

app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from registration.signals import user_registered


# project status code
STATUS_OPEN = 100
STATUS_DONE = 101
STATUS_CLOSED = 102


class RequestQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)

    def by(self, requester):
        return self.filter(created_by=requester)

    def opened(self):
        return self.filter(status=STATUS_OPEN)

    def category(self, cat):
        return self.filter(type=cat)


class SkillTag(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "SkillTag"
        verbose_name_plural = "Skill Tags"


class RequestSubCategory(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    description = models.TextField(blank=True)
    skill_tags = models.ManyToManyField(SkillTag, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.slug = slugify(self.name)
        super(RequestSubCategory, self).save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Request Sub Category"
        verbose_name_plural = "Request Sub Categories"


class RequestCategory(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    description = models.TextField(blank=True)
    sub_categories = models.ManyToManyField(RequestSubCategory, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.slug = slugify(self.name)
        super(RequestCategory, self).save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "RequestCategory"
        verbose_name_plural = "Request Categories"


class Request(models.Model):
    PROJECT_STATUS = (
        (STATUS_OPEN, _('Open')),
        (STATUS_DONE, _('Done')),
        (STATUS_CLOSED, _('Closed'))
    )
    title = models.CharField(max_length=200)
    type = models.ForeignKey(RequestCategory, blank=True, null=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    status = models.SmallIntegerField(choices=PROJECT_STATUS, blank=True, default=STATUS_OPEN)
    created_by = models.ForeignKey(User, related_name='requested_by')
    skills = models.ManyToManyField(SkillTag, blank=True, related_name='collaborators')
    collaborators = models.ManyToManyField(User, blank=True)
    publish = models.BooleanField(blank=True, default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # custom query set manager
    objects = RequestQuerySet.as_manager()

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.slug = slugify(self.title)
        super(Request, self).save(force_insert, force_update, using, update_fields)

    class Meta:
        verbose_name = "Request"
        verbose_name_plural = "Requests"
        ordering = ["-created"]


class Offer(models.Model):
    project = models.ForeignKey(Request, null=False, blank=False)
    offer_by = models.ForeignKey(User, null=False, blank=False)
    is_accepted = models.BooleanField(default=False)
    is_seen = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def is_rejected(self):
        return not self.is_accepted

    def __str__(self):
        return  self.offer_by.username+" Offerd "+self.project.title+" to "+self.project.created_by.username


class Rating(models.Model):
    project = models.ForeignKey(Request, null=False, blank=False)
    rated_user = models.ForeignKey(User, null=False, blank=False)
    score = models.SmallIntegerField()
    comment = models.CharField(null=False, max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Notification(models.Model):
    RECEIVED_OFFER = 200
    OFFER_ACCEPTED = 201
    OFFER_REJECTED = 202

    NOTIFICATION_TYPES = (
        (RECEIVED_OFFER, _('RECEIVED_OFFER')),
        (OFFER_ACCEPTED, _('OFFER_ACCEPTED')),
        (OFFER_REJECTED, _('OFFER_REJECTED')),
    )
    for_user = models.ForeignKey(User, null=False, blank=True)
    action_url = models.URLField(null=False, blank=False)
    type = models.SmallIntegerField(choices=NOTIFICATION_TYPES, blank=True, null=True)
    message = models.CharField(null=False, max_length=200, blank=False)
    is_seen = models.BooleanField(default=False, null=False)
    extra = models.ForeignKey(Offer, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, null=False)
    website = models.URLField(blank=True, null=False, default='')
    stackoverflow_account = models.URLField(blank=True, null=False, default='')
    github_account = models.URLField(blank=True, null=False, default='')
    twitter_account = models.URLField(blank=True, null=False, default='')
    google_plus_account = models.URLField(blank=True, null=False, default='')
    reputation = models.IntegerField(blank=True, null=False, default=0)
    about = models.TextField(blank=True, null=False, default='')
    location = models.CharField(max_length=140, null=False, blank=True, default='')
    career = models.CharField(max_length=140, null=False, blank=True, default='')
    company = models.CharField(max_length=140, null=False, blank=True, default='')
    profileView = models.IntegerField(blank=True, default=0, null=False)
    skills = models.ManyToManyField(SkillTag, blank=True, related_name='skills')

    def __str__(self):
        return self.user.username


def user_registered_callback(sender, user, request, **kwargs):
    profile = UserProfile(user=user)
    profile.save()


user_registered.connect(user_registered_callback)

app/forms.py
from django import forms
from django.contrib.auth.models import User

from app.models import Request, UserProfile


class ProjectForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Request
        fields = ('title', 'description', 'skills',)


class ProfileForm(forms.ModelForm):
    skills = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('career', 'company', 'website', 'about', 'location', 'stackoverflow_account', 'github_account',
                  'twitter_account', 'google_plus_account')

class AccountUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

app/templates/app/account_setting.html
{% extends "signed_in_base.html" %}


{% block content %}

<div class="container">
    <div class="row" style="margin-bottom: 25px;">

		<div class="col-sm-8">

                <form action="{% url 'edit_account' %}" method="POST">
                    {% csrf_token %}
                    User Name
                    <div class="form-group">
                        <input value="{{ user.username }}" placeholder="Username" name="username" type="text" class="form-control">
                    </div>
                    First Name
                    <div class="form-group">
                        <input value="{{ user.first_name }}" placeholder="First Name" name="first_name" type="text" class="form-control">
                    </div>
                    Last Name
                    <div class="form-group">
                        <input value="{{ user.last_name }}" placeholder="Last Name" name="last_name" type="text" class="form-control">
                    </div>
                    Email
                    <div class="form-group">
                        <input value="{{ user.email }}" placeholder="email" name="email" type="text" class="form-control">
                    </div>


                    <input class="btn btn-actions" type="submit" value="Update">
                </form>

        </div>
    </div>

	</div>

</div>


{% endblock %}

app/templates/app/dashboard.html
{% extends "signed_in_base.html" %}


{% block content %}

    {# FILTER RESULT MODAL#}
    <div id="filter_result_modal" class="modal fade" role="dialog">
        <div class="modal-dialog">
           <div class="modal-content">

              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Results</h4>
              </div>

              <div class="modal-body">
                <div class="content">
                      </div>
              </div>

           </div>
        </div>
    </div>
    {# END FILTER RESULT MODAL#}


    <div class="container">

        <!--MESSAGES-->
        <div class="panel col-md-12">
{#            {% if messages %}#}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
{#            {% endif %}#}
        </div>
        <!--END MESSAGES-->

        <div class="panel col-lg-8 col-md-8 col-md-offse-2 " style="background-color: rgba(207, 208, 212, 0.03);margin-bottom: 100px;padding-bottom: 100px; ">

              <div class="panel" >
                <form class="form-horizontal" role="form"  id="ro-form" data-toggle="validator" >

                    {% csrf_token %}

                    <div class="form-group">
                        <input style="font-size: 20px;height: 50px;font-family: exo;font-weight:900" id="id_title" class="form-control text " maxlength="200" name="request_title" placeholder="I'm Requesting" type="text" required>
                    </div>

                    <div  style="margin-bottom: 25px;" class="form-group">
                            <select  class="required form-control" id="id_type" name="request_category" >
                                    <option value="">Category of work</option>
                                    <option value="websites-it-and-software">Websites IT &amp; Software</option>
                                    <option value="mobile">Mobile</option>
                                    <option value="writing">Writing</option>
                                    <option value="graphics-design">Graphics Design</option>
                                    <option value="data-entry">Data Entry</option>
                            </select>
                     </div>

                    <div id="detail-Accordion-2">
                         <a data-toggle="collapse" data-parent="#accordion" class="app-link" style="font-size:17px;" href="#DetailsAccordion_2">
                            <i class="icon icon-angle-down"></i>
                               With Details
                        </a>

                        <div id="DetailsAccordion_2" class="collapse">

                            <div class="">
                                <label class="control-label" for="id_description">Description</label>
                                <textarea class="form-control" cols="40" id="id_description" name="request_description" rows="10"></textarea>
                            </div>

                             <div style="margin-top: 25px;margin-bottom: 25px;" >
                                <select style="width: 100%;" name="request_skills" class="form-control tags"  multiple="multiple">
                                </select>
                             </div>
                        </div>


                      </div>

                    <div id="InExchangeFor">

                        <a data-toggle="collapse" data-parent="#accordion" class="app-link" style="font-size:17px;" href="#InExchangeForAccordion">
                            <i class="icon icon-angle-down"></i>
                               In Exchange For
                        </a>
                        <div id="InExchangeForAccordion" class="collapse">
                                <div class="content field">
                                    {#  <h3 style="text-align: center;font-family: exo-light;font-size: 25px;color: #40465E;margin-top: 15px;">In Exchange For</h3>#}
                                    <div id="selected_offer"  class="app-project-list-item" style="display: none;margin-bottom: 15px;;">

                                    </div>
                                    <div class="panel" id="offer_filter_options">
                                         <div style="margin-bottom: 25px;" >
                                            <select name="project_category" id="project_category" class="form-control" >
                                                    <option selected="" value="-1">Category of work</option>
                                                    <option value="websites-it-and-software">Websites IT &amp; Software</option>
                                                    <option value="mobile">Mobile</option>
                                                    <option value="writing">Writing</option>
                                                    <option value="design">Design</option>
                                                    <option value="data-entry">Data Entry</option>
                                            </select>
                                        </div>

                                         <div  style="margin-bottom: 25px;display:none">
                                            <select name="project_subcategory" id="project_subcategory" class="form-control">
                                                <option value="-1" selected="selected">Select a job (Optional)</option>
                                            </select>
                                         </div>

                                         <div style="margin-bottom: 25px;" >
                                            <select style="width: 100%;" name="offer_skills" id="offer_skills" class="form-control tags"  multiple="">
                                            </select>
                                        </div>
                                            <i class="icon icon-search" style="display: none;float:right;font-size: 20px;margin: 0px;padding: 2px;height: inherit;position: relative;bottom: 20px;right: 5px;" id="search_offer"></i>
                                    </div>
                                    <div id="action_btns">
                                        <input style="margin-left: 250px;" class="btn btn-info" type="submit" id="math_me_btn" value="Match Me"> <br>
                                    </div>
                                </div>
                        </div>
                    </div>

                    <div id="action_btn_post">
                        <input style="margin-left: 250px;" class="btn btn-info" type="submit"  id="post_project_btn" value="Post"> <br>
                    </div>

                </form>

              </div>

              <div style="margin-top: 100px;" class="">
                  <ul class="nav nav-tabs">
                      <li class="active">
                          <a   href="#working-on" class="app-link" data-toggle="tab">Working On</a>
                      </li>
                      <li>
                          <a  href="#your-reqeusts" class="app-link" data-toggle="tab">Your Requests</a>
                      </li>
                  </ul>
              </div>

                <div class="tab-content">

                      <div class="tab-pane fade in active"  id="working-on">
                              {% if projects_working_on %}
                                    <h6 style="text-align: center;font-family: exo-light;font-size: 25px;color: #40465E;margin-top: 15px;">Working On</h6>
                                    {% for offer in projects_working_on %}
                                        <div class="app-project-list-item">
                                         <a href="{% url 'project_detail' offer.project.slug %}" >
                                            <div style="">
                                                    <a class="dashboard-project-title" href="{% url 'project_detail' offer.project.slug %}">{{ offer.project.title | truncatechars:"35" }}</a>
                                                    {% load app_tags_filters %}
                                                    <div>{{ offer.project.created |date }} <span class="tag" style="color: #FFF;float: right">{{ offer.project.status | display_status }}</span></div>
                                            </div>
                                        </a>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                      </div>

                      <div class="tab-pane fade"  id="your-reqeusts">

                          {% if my_projects %}
                            <div style="margin-top: 25px;">
                            <div class="" style="text-align: center">
                               <span style="text-align: center;font-family: exo-light;font-size: 25px;color: #40465E;margin-top: 15px;">Your Requests</span>
                            </div>

                            {% for project in my_projects %}
                                <a href="{% url 'project_detail' project.slug %}" >
                                    <div class="app-project-list-item">
                                            <a class="dashboard-project-title" href="{% url 'project_detail' project.slug %}">{{ project.title | truncatechars:"35" }}</a>
                                            {% load app_tags_filters %}
                                            <div>{{ project.created |date }} <span class="tag" style="color: #FFF;float: right">{{ project.status | display_status }}</span></div>
                                    </div>
                                </a>
                            {% endfor %}
                          </div>
                          {% else %}
                             You have no projects!
                          {% endif %}

                      </div>

                </div>
        </div>

        <div class="panel col-lg-4 col-md-4  " style="margin-top:25px;">

            <div class="PANEL-HEADING" style="text-align: center;font-family: exo-light;font-size: 25px;">Suggested Projects </div>
            <div class="panel-body">
                {% if suggestions %}
                    {% for project in suggestions %}
                         <a href="{% url 'project_detail' project.slug %}" >
                            <div class="app-project-list-item">
                                    <a class="dashboard-project-title" href="{% url 'project_detail' project.slug %}">{{ project.title | truncatechars:"35" }}</a>
                                    <div>{{ project.created |date }} </div>
                            </div>
                        </a>

                    {% endfor %}

                {% else %}
                    <p>No projects are available.</p>
                {% endif %}

            </div>

        </div>

    </div>

{% endblock %}

app/templates/app/editProfile.html
{% extends "signed_in_base.html" %}


{% block content %}

<div class="container">
    <div class="row" style="margin-bottom: 25px;">

        <div class="col-sm-4">
			<div class="profile-sidebar" style="background: #CFD0D4;color: #41475E;">

				<div class="profile-userpic">

                  {% load avatar_tags %}
{#                    <a href="{% url 'avatar_change' %}"1> <span style="color:gray" class="glyphicon glyphicon-pencil"></span> </a>#}
                    <div class="col-xs-6 col-xs-offset-3" style="padding-left:100px; margin-bottom: 10px;">
                        {% avatar data.profile.user 150 class="img-circle img-responsive" id="user_avatar" %}
                    </div>

				</div>

                <!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="">
						<h3 style="margin: 0px">{{  data.profile.user.first_name   }}  {{  data.profile.user.last_name   }}</h3>
						{{  data.profile.user.username   }}<br>
						{{  data.profile.career   }} <br>

					</div>

				</div>
                <div>
                        <div class="ntag">
                            {{  data.profile.reputation }} Reputations

                        </div>

                        <div class="ntag">
                               {{ data.num_requests }} Request
                        </div>

                        <div class="ntag">
                              {{ data.num_offers }} Offers

                        </div>
                </div>

                {% if data.profile.user == user %}
			    	<div class="profile-usermenu">
                        <ul class="nav">
                            <li >
                                <a href="{% url 'user_profile'  user.username %}">
                                    <i class="glyphicon glyphicon-home"></i>
                                Overview </a>
                            </li>
                            <li>
                                <a href="{% url 'edit_account' %}">
                                <i class="glyphicon glyphicon-user"></i>
                                Account Settings </a>
                            </li>
                            <li class="active">
                             <a href="{% url 'edit_profile'%}">
                                <i class="glyphicon glyphicon-pencil"></i>
                                Edit Profile </a>
                            </li>
                            <li>
                                <a href="{% url 'auth_password_change' %}">
                                <i class="glyphicon glyphicon-lock"></i>
                                Change Password
                                </a>
                            </li>
					    </ul>
    				</div>
                {% endif %}
			</div>
		</div>

		<div class="col-sm-8">

                <form action="{% url 'edit_profile' %}" method="POST">
                    {% csrf_token %}

                    <div class="form-group">
                            <textarea name="about" id="" class="form-control"    placeholder="Your Bio"  cols="30" rows="10">{{ data.profile.about }}</textarea>
                    </div>

                    <div class="form-group">
                        <input value="{{ data.profile.company }}" placeholder="Company" name="company" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <input value="{{ data.profile.location }}" placeholder="Location" name='location' type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <input value="{{  data.profile.website  }}" placeholder="Website" name="website" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <input value="{{  data.profile.stackoverflow_account  }}" name="stackoverflow_account" placeholder="Stackoverflow" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <input value="{{  data.profile.twitter_account  }}"  name="twitter_account" placeholder="Twitter" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <input value="{{  data.profile.github_account  }}" name="github_account" placeholder="Github" type="text" class="form-control">
                    </div>

                    <div class="form-group">
                        <input value="{{  data.profile.google_plus_account  }}" name="google_plus_account" placeholder="Google Plus" type="text" class="form-control">
                    </div>

                    <div>
                        {% if data.skills %}
                            {% for skill in data.skills %}
                                    <li class="tag">{{skill.name}}</li>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                           <select name="skills" class="form-control tags"  multiple="multiple">
                           </select>
                    </div>


                    <input class="btn btn-actions" type="submit" value="Update">
                </form>

        </div>
    </div>

	</div>

</div>


{% endblock %}

app/templates/app/editProject.html
{% extends "signed_in_base.html" %}


{% block content %}

<div class="container" style="margin-bottom: 100px;">

    <div>

        {{ form.errors }}
    </div>

<form class="form-horizontal col-lg-7 col-md-7" id="create_request_form" role="form" method="post" action="{% url 'edit_view' instance.slug%}">

        {% csrf_token %}
        <div class="form-group">
            <label class="control-label" for="id_type">Type</label><br/>
            <select class="form-control" id="id_type" name="type">
                <option value="" selected="selected">Select Project Type</option>
                <option
                        {% if instance.type.slug == 'websites-it-and-software'  %}selected='selected'{% endif %}
                        value="websites-it-and-software">Websites IT &amp; Software
                </option>
                 <option
                        {% if instance.type.slug == 'mobile'  %}selected='selected'{% endif %}
                        value="mobile">Mobile
                </option>

                <option
                        {% if instance.type.slug == 'graphics-design'  %}selected='selected'{% endif %}
                        value="graphics-design">Graphics Design
                </option>
                <option
                        {% if instance.type.slug == 'writing'  %}selected='selected'{% endif %}
                        value="writing">Writing
                </option>
                <option
                        {% if instance.type.slug == 'data-entry'  %}selected='selected'{% endif %}
                        value="writing">Data Entry
                </option>
            </select>
             <br/>
        </div>

        <div class="form-group">
            <input value="{{ instance.title }}" style="font-size:20px;height: 50px;font-family: exo;font-weight:900" id="id_title" class="form-control" maxlength="200" name="title" placeholder="I'm Requesting" type="text"><br>
        </div>

        <div class="form-group">
                  <label class="control-label" for="id_description">Description</label>
                    <br/>
                  <textarea class="form-control" cols="40" id="id_description" name="description" rows="10">{{ instance.description }}</textarea>
                  <br/>
         </div>

        <div>
            {% if instance.skills.all %}
                {% for skill in instance.skills.all %}
                        <li class="tag">{{skill.name}}</li>
                {% endfor %}
            {% endif %}
        </div>
        <div class="form-group">
              <select multiple="multiple" class="form-control tags" id="id_skills" name="skills"></select>
        </div>


        <div class="panel-body  ">
            <a  href="{%  url 'project_detail' instance.slug%}" class="btn btn-danger" type="submit" >Cancel</a>
            <input  style="float: right" class="btn btn-info" type="submit" value="Update" />
      </div>


</form>

</div>


<script>


</script>
{% endblock %}

app/templates/app/explore_auth.html
{% extends "signed_in_base.html" %}


{% block content %}

    {% include 'app/explore_projects.html' %}


{% endblock %}